### ISSUE TITLE
Replaced with the wrong game ID

### ISSUE THREAD

**Issue by bennyz327** [RoyalShooter/Playnite-DLsite-Metadata-Name-fix-script#1]
Test game name: 宇宙海賊サラ
Convert to: RJ390903
The correct ID is: RJ033572
Is this a bug or am I using it incorrectly?

**Comment by RoyalShooter** [comment]
> Test game name: 宇宙海賊サラ Convert to: RJ390903 The correct ID is: RJ033572 Is this a bug or am I using it incorrectly?

Can you give me the sort name under the edit game page in playnite. Also can you give me the path of the game exe. Thanks.

**Comment by bennyz327** [comment]
Because the game is manually added for testing, I only fills in the game name in my first test, and the sort name and game path are both empty
I also tested the following conditions

First try(A-1)
game name:
宇宙海賊サラ
installation path:
empty
Sort Name:
empty
Test result: incorrect 
(Name convert to RJ390903)

A-2
game name:
123456789
installation path:
empty
Sort Name:
宇宙海賊サラ
Test result: incorrect 
(Name convert to RJ390903)

A-3
game name:
123456789
installation path:
E:\bendrive_sync\Rdesgin\Game\!DLsite_RJ\GD220223_LILITH_INC\2.BLACK LiLiTH\20070824_宇宙海賊サラ
Sort Name:
empty
Test result: incorrect 
(Name convert to RJ094481)


B-1
game name:
宇宙海賊サラ
installation path:
empty
Sort Name:
宇宙海賊サラ
Test result: correct

B-2
game name:
宇宙海賊サラ
installation path:
E:\bendrive_sync\Rdesgin\Game\!DLsite_RJ\GD220223_LILITH_INC\2.BLACK LiLiTH\20070824_宇宙海賊サラ
Sort Name:
empty
Test result: correct

B-3
game name:
123456789
installation path:
E:\bendrive_sync\Rdesgin\Game\!DLsite_RJ\GD220223_LILITH_INC\2.BLACK LiLiTH\20070824_宇宙海賊サラ
Sort Name:
宇宙海賊サラ
Test result: incorrect 
(Name convert to RJ094481)

**Comment by RoyalShooter** [comment]
You do not have to fill in the sort name, I used the sort name field to export the debug data. you should see something like RJ123456 = path name = name of the game.

I design the script to grab the longest name in the path since I have no way to understand which folder is the game name. In your case, I believe that would become an error with \GD220223_LILITH_INC\ this is used as the search name. then the script proceeds to search with the auto detect name field "宇宙海賊サラ" and this entry becomes successful.

This explains why B1 B2 is correct and also A3 B3 is incorrect, because A3 B3 used 123456789 as search and that is the dev name of game RJ094481.

For test A1 I am guessing because you create the game by manually, without the path it may have created some bugs behind.

This way of testing should work MOST of the time and ending up just one or two entries you have to correct again, I will try to fix the script behaviour with the next update to improve its success rate.

I suggest you add your games by Scan automatically or by drag and drop the folder into playnite, this will ensure the exe path is entered and correct.

**Comment by bennyz327** [comment]
Thank you very much for your response
I can probably understand how this script works and why I'm getting errors
I will continue to test on different games ,and use your script with both path and the game title instead of only using game title!

But If this script can replace the name to RJ code that only have a game title in the future?
Maybe like: A game just have a simple and pure title in Playnite, then use this title as a keyword to search and grab the RJ code on the DLsite, is it possible?
Since I'm not a programmer, forgive me if I give a stupid idea.

P.S.
For some personal reasons, most of my games are compressed in the Rar file format, which is why I can't use automatic detection and use manual add.
I've always put a game title into google search and copied the RJ code on the DLsite and pasted back to Playnite for game metadata scraper for each game, that's why I'm so excited to see you make a script like this!
Really appreciate you for making this script!

**Comment by RoyalShooter** [comment]
> Thank you very much for your response I can probably understand how this script works and why I'm getting errors I will continue to test on different games ,and use your script with both path and the game title instead of only using game title!
> 
> But If this script can replace the name to RJ code that only have a game title in the future? Maybe like: A game just have a simple and pure title in Playnite, then use this title as a keyword to search and grab the RJ code on the DLsite, is it possible? Since I'm not a programmer, forgive me if I give a stupid idea.
> 
> P.S. For some personal reasons, most of my games are compressed in the Rar file format, which is why I can't use automatic detection and use manual add. I've always put a game title into google search and copied the RJ code on the DLsite and pasted back to Playnite for game metadata scraper for each game, that's why I'm so excited to see you make a script like this! Really appreciate you for making this script!

Yes, making it using the name field only to search is possible, but I would have to either create a new script or write a new UI for the script so it takes user input and know what to search or not. In short, it takes time for me to learn and create the setting page so then it can accept user input for changing what to search.
